### ISSUE TITLE
Non-default theme icons don't render

### ISSUE THREAD

**Issue by IronPiston** [ElXreno/multimc#1] opened 2020-01-10 01:59 UTC
MultiMC version: `multimc-0.6.7-5.fc31.x86_64`

Setting icons under Settings -> MultMC -> User Interface to anything besides the default cause them to not render at all.

![image](https://user-images.githubusercontent.com/11603684/72119558-739c2280-331a-11ea-801e-9caffa9ebc1f.png)

**Comment by ElXreno** [comment] 2020-01-10 09:36
Can't reproduce in Fedora 31 GNOME and KDE with stock icons. Report this to the upstream.

![Screenshot_fedora31_2020-01-10_12:34:33](https://user-images.githubusercontent.com/40758597/72142459-c838af80-33a5-11ea-81c8-26cfbd8e79de.png)

**Comment by ElXreno** [comment] 2020-02-09 09:49
@IronPiston try MultiMC 0.6.8, maybe it fixed in this version.

**Comment by IronPiston** [comment] 2020-04-09 00:22
Sorry for the late reply, updating seems to have fixed the issue. Thanks!

**Closed as completed** 2020-04-09 00:22 UTC
